// broken dot product function, can you find the bug?
// again, generated by deepseek, modified by me (credit where credit is due)

#include <stdio.h>
#include <stdlib.h>

// Function to compute the dot product of two vectors
double dotProduct(double* vector1, double* vector2, int length) {
    double result = 0.0;
    for (int i = 0; i < length; i++) {
        result += vector1[i] * vector2[i];
    }
    return result;
}

int main() {
    int length;

    // Input the length of the vectors
    printf("Enter the length of the vectors: ");
    scanf("%d", &length);

    // Allocate memory for the vectors
    double* vector1 = (double*)malloc(length * sizeof(int));
    double* vector2 = (double*)malloc(length * sizeof(int));

    // Input elements of the first vector
    printf("Enter elements of the first vector:\n");
    for (int i = 0; i < length; i++) {
        scanf("%lf", &vector1[i]);
    }

    // Input elements of the second vector
    printf("Enter elements of the second vector:\n");
    for (int i = 0; i < length; i++) {
        scanf("%lf", &vector2[i]);
    }

    // Compute the dot product
    double result = dotProduct(vector1, vector2, length);

    // Output the result
    printf("The dot product of the two vectors is: %.2f\n", result);

    // Free allocated memory
    free(vector1);
    free(vector2);

    return 0;
}
