#include <stdio.h>
#include <stdlib.h>
// generated by deepseek, modified by me slightly

// Function to compute the dot product of two vectors
int dotProduct(int* vector1, int* vector2, int length) {
    int result = 0;
    for (int i = 0; i < length; i++) {
        result += vector1[i] * vector2[i];
    }
    return result;
}

int main() {
    int length;

    // Input the length of the vectors
    printf("Enter the length of the vectors: ");
    scanf("%d", &length);

    // Allocate memory for the vectors
    int vector1[length];
    int vector2[length];

    // Input elements of the first vector
    printf("Enter elements of the first vector:\n");
    for (int i = 0; i < length; i++) {
        scanf("%d", &vector1[i]);
    }

    // Input elements of the second vector
    printf("Enter elements of the second vector:\n");
    for (int i = 0; i < length; i++) {
        scanf("%d", &vector2[i]);
    }

    // Compute the dot product
    int result = dotProduct(vector1, vector2, length);

    // Output the result
    printf("The dot product of the two vectors is: %d\n", result);

    return 0;
}
