// insertion sort using macros

#define AAA int 
#define AAAAAAH_WE_RE_ALL_GONNA_DIE main(int argc, char** argv) 
#define CURSE_YOU printf 
#define LEFTLEFTLEFT ( 
#define RIGHTRIGHRIGHT ) 
#define UPUP + 
#define UPUPUPUP ++
#define AAAAAAAAAAAAAAAAAAAAAAAUGHHIGUGUGH void
#define THERESNOTHINGLEFT { 
#define IWASRIGHT  } 
#define THISISTHEEND ; 
#define GAHHHHHH [ 
#define IM_DYING ] 
#define LET_ME_BE_FREE while 
#define ASDFDSFSS for 
#define AAAAAAAUGH = 
#define DOWN -  
#define THISSUCKSASDFASDFADSASDF [] 
#define AAAAAAAAAAAAAAASDF if 
#define LETMEGOOOOOO , 
#define LOWERLOWER < 
#define HIGHERHIGHER > 
#define FTS >=  
#define NONONONONONO !=  
#define OHNONONONO return 
#define OHMYLAWD &&
#define GIVEMETHEMONEY scanf

#include  <stdio.h> 
#include  <math.h> 




AAAAAAAAAAAAAAAAAAAAAAAUGHHIGUGUGH insertionSort LEFTLEFTLEFT  AAA  arr THISSUCKSASDFASDFADSASDF   LETMEGOOOOOO   AAA  N RIGHTRIGHRIGHT   THERESNOTHINGLEFT 

    // Starting from the second element
     ASDFDSFSS   LEFTLEFTLEFT  AAA  i  AAAAAAAUGH  1 THISISTHEEND  i  LOWERLOWER  N THISISTHEEND  i UPUPUPUP  RIGHTRIGHRIGHT   THERESNOTHINGLEFT 
         AAA  key  AAAAAAAUGH  arr GAHHHHHH i IM_DYING  THISISTHEEND 
         AAA  j  AAAAAAAUGH  i   DOWN   1 THISISTHEEND 

        // Move elements of arr GAHHHHHH 0..i  DOWN  1 IM_DYING   LETMEGOOOOOO  that are
          // greater than key  LETMEGOOOOOO  to one position to
          // the right of their current position
         LET_ME_BE_FREE   LEFTLEFTLEFT j  FTS  0 OHMYLAWD arr GAHHHHHH j IM_DYING   HIGHERHIGHER  key RIGHTRIGHRIGHT   THERESNOTHINGLEFT 
            arr GAHHHHHH j  UPUP  1 IM_DYING   AAAAAAAUGH  arr GAHHHHHH j IM_DYING  THISISTHEEND 
            j  AAAAAAAUGH  j   DOWN   1 THISISTHEEND 
         IWASRIGHT 

        // Move the key to its correct position
        arr GAHHHHHH j  UPUP  1 IM_DYING   AAAAAAAUGH  key THISISTHEEND 
     IWASRIGHT 
 IWASRIGHT 

AAA AAAAAAH_WE_RE_ALL_GONNA_DIE  THERESNOTHINGLEFT 
    
      AAAAAAAAAAAAAAASDF   LEFTLEFTLEFT argc  NONONONONONO  2 RIGHTRIGHRIGHT  THERESNOTHINGLEFT 
         CURSE_YOU  LEFTLEFTLEFT "invalid format\n" RIGHTRIGHRIGHT  THISISTHEEND 
         OHNONONONO  1 THISISTHEEND 
     IWASRIGHT 
     AAA  N  AAAAAAAUGH  atoi  LEFTLEFTLEFT  argv GAHHHHHH 1 IM_DYING   RIGHTRIGHRIGHT   THISISTHEEND 
     AAA  arr GAHHHHHH N IM_DYING  THISISTHEEND 
    
     ASDFDSFSS   LEFTLEFTLEFT  AAA  i  AAAAAAAUGH  0 THISISTHEEND  i  LOWERLOWER  N THISISTHEEND  i UPUPUPUP  RIGHTRIGHRIGHT  THERESNOTHINGLEFT 
        GIVEMETHEMONEY LEFTLEFTLEFT "%d"  LETMEGOOOOOO  &arr GAHHHHHH i IM_DYING  RIGHTRIGHRIGHT  THISISTHEEND 
     IWASRIGHT 

     CURSE_YOU  LEFTLEFTLEFT "Unsorted array: " RIGHTRIGHRIGHT  THISISTHEEND 
     ASDFDSFSS   LEFTLEFTLEFT  AAA  i  AAAAAAAUGH  0 THISISTHEEND  i  LOWERLOWER  N THISISTHEEND  i UPUPUPUP  RIGHTRIGHRIGHT   THERESNOTHINGLEFT 
         CURSE_YOU  LEFTLEFTLEFT "%d "  LETMEGOOOOOO  arr GAHHHHHH i IM_DYING  RIGHTRIGHRIGHT  THISISTHEEND 
     IWASRIGHT 
     CURSE_YOU  LEFTLEFTLEFT "\n" RIGHTRIGHRIGHT  THISISTHEEND 

    // Calling insertion sort on array arr
    insertionSort LEFTLEFTLEFT arr  LETMEGOOOOOO  N RIGHTRIGHRIGHT  THISISTHEEND 

     CURSE_YOU  LEFTLEFTLEFT "Sorted array: " RIGHTRIGHRIGHT  THISISTHEEND 
     ASDFDSFSS   LEFTLEFTLEFT  AAA  i  AAAAAAAUGH  0 THISISTHEEND  i  LOWERLOWER  N THISISTHEEND  i UPUPUPUP  RIGHTRIGHRIGHT   THERESNOTHINGLEFT 
         CURSE_YOU  LEFTLEFTLEFT "%d "  LETMEGOOOOOO  arr GAHHHHHH i IM_DYING  RIGHTRIGHRIGHT  THISISTHEEND 
     IWASRIGHT 
     CURSE_YOU  LEFTLEFTLEFT "\n" RIGHTRIGHRIGHT  THISISTHEEND 

     OHNONONONO  0 THISISTHEEND 
 IWASRIGHT 